---
- name: Setting up my server
  hosts: servers
  become: yes
  remote_user: ubuntu
  vars_prompt:
      - name: "http_port"
        prompt: "HTTP Port number"
  

  tasks:
    - name: Update system packages
      raw: sudo apt update -y

    - name: Install Apache2
      apt:
        name: apache2
        state: latest

    - name: Make sure Apache is running
      systemd:
        name: apache2
        state: started
